/**
 * ChallengeHmacVectorTest.kt — JVM test that Crypto.buildChallengeAad +
 * Crypto.computeChallengeHmac reproduce the cross-language vectors in
 * src/test/resources/m3b_challenge_vectors.json byte-for-byte.
 *
 * The vectors are generated by scripts/gen-m3b-challenge-vectors.js, which
 * imports the AUTHORITATIVE Node spec from src/lan-challenge.js. So this test
 * is the B-6 cross-language pre-heat: Kotlin AAD/HMAC == Node AAD/HMAC for
 * every (key, id, nonce, purpose, ts, fingerprint) tuple, covering all three
 * purposes. The Android-only ESP/PIN-Activity plumbing is exercised on-device
 * (B-6); this guards the pure crypto that the fallback path depends on.
 *
 * Run: ./gradlew app:testDebugUnitTest
 */

package com.passman.pair

import org.json.JSONArray
import org.junit.Test
import org.junit.Assert.assertArrayEquals

class ChallengeHmacVectorTest {

    private fun loadVectors(): JSONArray {
        val stream = javaClass.classLoader!!.getResourceAsStream("m3b_challenge_vectors.json")
            ?: throw IllegalStateException("m3b_challenge_vectors.json not found in test resources")
        return JSONArray(stream.reader().readText())
    }

    @Test
    fun kotlin_aad_and_hmac_match_node_vectors() {
        val arr = loadVectors()
        assertTrue("vectors file non-empty", arr.length() > 0)
        for (i in 0 until arr.length()) {
            val v = arr.getJSONObject(i)
            val label = v.getString("label")
            val key = hexToBytes(v.getString("device_hmac_key_hex"))
            val id = v.getString("id")
            val nonce = hexToBytes(v.getString("nonce_hex"))
            val purpose = v.getString("purpose")
            val ts = v.getLong("ts_ms")
            val fpRaw = hexToBytes(v.getString("fingerprint_raw_hex"))
            val expectedAad = hexToBytes(v.getString("aad_hex"))
            val expectedHmac = hexToBytes(v.getString("hmac_hex"))

            val aad = Crypto.buildChallengeAad(id, nonce, purpose, ts, fpRaw)
            assertArrayEquals("[$label] AAD matches Node", expectedAad, aad)

            // computeChallengeHmac is the §7 fallback path (K_pin, no Keystore).
            // The vectors use the same HMAC algorithm, so the same key verifies
            // both the bio path semantics and the fallback computation.
            val hmac = Crypto.computeChallengeHmac(key, aad)
            assertArrayEquals("[$label] HMAC matches Node", expectedHmac, hmac)
        }
    }

    private fun hexToBytes(s: String): ByteArray {
        val hex = s.replace(" ", "")
        return ByteArray(hex.length / 2) {
            ((Character.digit(hex[it * 2], 16) shl 4) or Character.digit(hex[it * 2 + 1], 16)).toByte()
        }
    }

    private fun assertTrue(msg: String, cond: Boolean) = org.junit.Assert.assertTrue(msg, cond)
}
