/**
 * CryptoPairingTest.kt — JVM unit tests for the M3'-A pieces in Crypto.kt
 * (rollingPin / verifyPin / PairAttemptTracker) plus a cross-language byte
 * check against vectors generated by Node from secure.js.
 *
 * Why this matters: the reviewer flagged "Kotlin rollingPin / fingerprintHex
 * never tested against secure.js" as a M3'-A blocker. This test loads
 * m3_pairing_vectors.json (generated by scripts/gen-m3-pairing-vectors.js)
 * and confirms that, given the same pair_secret and window, Kotlin's
 * rollingPin produces the same 6-digit PIN as the JS reference.
 *
 * Run: ./gradlew app:testDebugUnitTest
 */

package com.passman.pair

import org.junit.Test
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.assertFalse
import org.json.JSONArray

class CryptoPairingTest {

    private fun loadVectors(name: String): JSONArray {
        val stream = javaClass.classLoader!!.getResourceAsStream(name)
            ?: throw IllegalStateException("$name not found in test resources")
        return JSONArray(stream.reader().readText())
    }

    private fun hexToBytes(s: String): ByteArray {
        val hex = s.replace(" ", "")
        return ByteArray(hex.length / 2) {
            ((Character.digit(hex[it * 2], 16) shl 4) or Character.digit(hex[it * 2 + 1], 16)).toByte()
        }
    }

    // ---------- rollingPin cross-language byte check ----------

    @Test
    fun rollingPin_matches_jsReference() {
        val arr = loadVectors("m3_pairing_vectors.json")
        for (i in 0 until arr.length()) {
            val v = arr.getJSONObject(i)
            // The vector file mixes rollingPin entries with fingerprint entries
            // (see fingerprintHex_matches_jsReference below). Skip ones that
            // aren't rollingPin shape — mirror that test's `has()` guard.
            if (!v.has("pair_secret_hex")) continue
            val pairSecret = hexToBytes(v.getString("pair_secret_hex"))
            val w = v.getLong("w")
            val expected = v.getString("pin")
            val got = Crypto.rollingPin(pairSecret, w)
            assertEquals(
                "rollingPin mismatch at vector $i (w=$w): JS expected=$expected, Kotlin got=$got",
                expected, got
            )
        }
    }

    // ---------- verifyPin ----------

    @Test
    fun verifyPin_acceptsCurrentWindow() {
        val secret = ByteArray(32) { it.toByte() }
        val w = 12345L
        val pin = Crypto.rollingPin(secret, w)
        assertEquals(w, Crypto.verifyPin(pin, w, secret))
    }

    @Test
    fun verifyPin_acceptsSlackWindow() {
        val secret = ByteArray(32) { (it + 5).toByte() }
        val w = 12345L
        // PIN generated for w-1 should still be accepted when client submits as w
        // (the verifier tries w-1..w+1).
        val pinWMinus1 = Crypto.rollingPin(secret, w - 1)
        val matched = Crypto.verifyPin(pinWMinus1, w, secret)
        assertNotNull("PIN from w-1 should match at slack ±1", matched)
        assertEquals(w - 1, matched)
    }

    @Test
    fun verifyPin_rejectsOutOfSlack() {
        val secret = ByteArray(32) { (it + 7).toByte() }
        val w = 12345L
        val pinW3 = Crypto.rollingPin(secret, w - 3)
        // Submit a PIN derived for w-3 but tell the server w. Slack ±1 means
        // it only tries w-1..w+1, so w-3 is out of slack.
        val matched = Crypto.verifyPin(pinW3, w, secret)
        assertNull("PIN from w-3 must not match at default skew=1", matched)
    }

    @Test
    fun verifyPin_rejectsWrongPin() {
        val secret = ByteArray(32) { (it * 3).toByte() }
        val w = 12345L
        val matched = Crypto.verifyPin("000000", w, secret)
        // Extremely unlikely "000000" matches any of w-1, w, w+1 for this secret,
        // but we don't bet on it: skew by enough that the PIN is definitely wrong.
        // Compute the actual PIN, flip a digit, and submit.
        val real = Crypto.rollingPin(secret, w)
        // Flip the first digit by +1 mod 10 — pure Char arithmetic, no
        // digitToChar() (which is Int.digitToChar() in stdlib, not Char.).
        val c0 = real.first()
        val c0p = if (c0 == '9') '0' else (c0 + 1)
        val tampered = c0p + real.substring(1)
        // tampered may rarely collide if the increment lands on another window's
        // PIN; the deterministic check below is safer:
        val pinForW = Crypto.rollingPin(secret, w)
        val pinForWPlus1 = Crypto.rollingPin(secret, w + 1)
        val pinForWMinus1 = Crypto.rollingPin(secret, w - 1)
        val deliberate = if (tampered != pinForW && tampered != pinForWPlus1 && tampered != pinForWMinus1) tampered else "999999"
        assertNull("wrong PIN must not match any window", Crypto.verifyPin(deliberate, w, secret))
    }

    // ---------- PairAttemptTracker ----------

    @Test
    fun tracker_freshNotLocked() {
        val tr = Crypto.PairAttemptTracker(maxFailures = 3, windowMs = 1000)
        assertFalse(tr.isLocked())
        assertEquals(0L, tr.unlockInMs())
    }

    @Test
    fun tracker_locksAtThreshold() {
        var now = 1_000_000L
        val tr = Crypto.PairAttemptTracker(
            maxFailures = 3, windowMs = 1000, clock = { now }
        )
        tr.recordFailure(); tr.recordFailure()
        assertFalse("2 failures should not lock", tr.isLocked())
        tr.recordFailure()
        assertTrue("3 failures should lock", tr.isLocked())
        // unlockInMs should be close to windowMs (within tiny epsilon since
        // we fake the clock and all 3 failures were at the same tick).
        assertEquals(1000L, tr.unlockInMs())
    }

    @Test
    fun tracker_unlocksAfterWindow() {
        var now = 1_000_000L
        val tr = Crypto.PairAttemptTracker(
            maxFailures = 3, windowMs = 1000, clock = { now }
        )
        repeat(3) { tr.recordFailure() }
        assertTrue(tr.isLocked())
        now += 1_001L
        assertFalse("after window expires, should not be locked", tr.isLocked())
    }

    @Test
    fun tracker_resetClearsFailures() {
        val tr = Crypto.PairAttemptTracker(maxFailures = 3, windowMs = 1000)
        tr.recordFailure(); tr.recordFailure(); tr.recordFailure()
        assertTrue(tr.isLocked())
        tr.reset()
        assertFalse(tr.isLocked())
        assertEquals(0L, tr.unlockInMs())
    }

    // ---------- fingerprintHex cross-language ----------

    @Test
    fun fingerprintHex_matches_jsReference() {
        val arr = loadVectors("m3_pairing_vectors.json")
        for (i in 0 until arr.length()) {
            val v = arr.getJSONObject(i)
            if (!v.has("fingerprint_of_pub_hex")) continue
            val pub = hexToBytes(v.getString("fingerprint_of_pub_hex"))
            val expected = v.getString("fingerprint")
            assertEquals(
                "fingerprintHex mismatch at vector $i",
                expected, Crypto.fingerprintHex(pub)
            )
        }
    }
}