plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization") version "2.0.21"
}

android {
    namespace = "com.passman.pair"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.passman.pair"
        // AOAP UsbAccessory has been available since API 12, but we lift the floor
        // to 21 (Android 5.0) so we get unrestricted Kotlin stdlib + later (M4)
        // EncryptedSharedPreferences without legacy multidex pain.
        minSdk = 21
        targetSdk = 35
        versionCode = 1
        versionName = "0.3-m1"
    }

    buildTypes {
        debug {
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = false
            // M1 ships unsigned debug only. M5 will add a real signing config.
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    // M1 doesn't need any layouts — the Activity uses contentless windows.
    buildFeatures {
        viewBinding = false
    }
}

dependencies {
    // Kept deliberately minimal for M1. Tink + EncryptedSharedPreferences land in M2/M4
    // (already noted in PROGRESS.md install-deps blocker).
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")

    // BiometricPrompt — used by BiometricDemoActivity for fingerprint validation PoC.
    // Pre-empted from M3 (CHALLENGE/RESPONSE flow) so we hit OEM-specific landmines
    // (Xiaomi MIUI fingerprint quirks) before they block protocol work.
    implementation("androidx.biometric:biometric:1.2.0-alpha05")

    // M1' (Wi-Fi hotspot route, ADR-002) — Ktor as on-phone HTTP server.
    // CIO engine instead of Netty: smaller APK (~1.5MB vs 3MB), no servlet
    // baggage, simpler DEX config. content-negotiation + kotlinx-json for
    // typed JSON request/response models.
    implementation("io.ktor:ktor-server-core:2.3.13")
    implementation("io.ktor:ktor-server-cio:2.3.13")
    implementation("io.ktor:ktor-server-content-negotiation:2.3.13")
    implementation("io.ktor:ktor-server-websockets:2.3.13")
    implementation("io.ktor:ktor-serialization-kotlinx-json:2.3.13")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")

    // M2' (ADR-002) — encrypted channel primitives, mirroring src/public/js/secure.js:
    //   X25519 ECDH → HKDF-SHA256 → AES-256-GCM.
    // Tink supplies Hkdf + X25519; AES-GCM goes through javax.crypto.Cipher
    // (NOT Tink AesGcmJce, which would prepend its own IV — see Crypto.kt header).
    implementation("com.google.crypto.tink:tink-android:1.13.0")

    // M2' interop unit test — verifies Crypto.SecureChannel.open() decrypts
    // wire frames produced by src/public/js/secure.js (vectors generated by
    // scripts/gen-m2-interop-vectors.js into src/test/resources/).
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20231013")
}
